name: Helmsman CI Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  helmsman-eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -e .
          pip install pyyaml scikit-learn
      - name: Run evaluation
        run: |
          mkdir -p helmsman/data/runs ci/out
          python -m helmsman.core.orchestrator \
            --contracts_dir helmsman/contracts/builtin \
            --packs helmsman/packs/smoke_ambiguous_en.jsonl \
            --prompts helmsman/prompts/v1.yaml \
            --model ${{ github.sha }} \
            --out helmsman/data/runs/${{ github.sha }}_smoke.jsonl
      - name: Compare with baseline
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          # On first run, create baseline file by copying the generated run
          # In a real project you would store a baseline file in the repo
          cp helmsman/data/runs/${{ github.sha }}_smoke.jsonl ci/baseline_smoke.jsonl
          python -m helmsman.core.diff \
            --a ci/baseline_smoke.jsonl \
            --b helmsman/data/runs/${{ github.sha }}_smoke.jsonl \
            --gates helmsman/ci/gates.yaml || true